TRAIN-Calculator/ViewModels/PayrollViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TRAIN_Calculator.Models;

namespace TRAIN_Calculator.ViewModels
{
    public class PayrollViewModel
    {
        public PaySlip PaySlips { get; set; }
        public List<PayrollCompensationViewModel> Compensations { get; set; }
        public List<PayrollDeMinimisViewModel> DeMinimis { get; set; }
        public List<PayrollDeductionViewModel> Deductions { get; set; }
    }

    public class PayrollViewModelItem
    {
        public decimal Value { get; set; }
    }

    public class PayrollCompensationViewModel : PayrollViewModelItem
    {
        public CompensationType Compensation { get; set; }
    }

    public class PayrollDeMinimisViewModel : PayrollViewModelItem
    {
        public DeMinimisType DeMinimis { get; set; }
    }

    public class PayrollDeductionViewModel : PayrollViewModelItem
    {
        public DeductionType Deduction { get; set; }
    }

}

TRAIN-Calculator/Controllers/PayrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TRAIN_Calculator.ViewModels;
using TRAIN_Calculator.Models;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.IO;
using System.Reflection;
using System.ComponentModel.DataAnnotations;

namespace TRAIN_Calculator.Controllers
{
    public class PayrollController : Controller
    {
        // GET: Payroll
        public ActionResult Index(PayrollViewModel model)
        {
            model.PaySlips = model.PaySlips ?? new PaySlip();
            model.Compensations = model.Compensations ?? new List<PayrollCompensationViewModel>();
            model.Deductions = model.Deductions ?? new List<PayrollDeductionViewModel>();
            model.DeMinimis = model.DeMinimis ?? new List<PayrollDeMinimisViewModel>();

            SetDropdowns();

            return View(model);
        }

       

        [HttpPost]
        public ActionResult Calculate(PayrollViewModel model)
        {
            model.PaySlips = model.PaySlips;
            model.Compensations = model.Compensations ?? new List<PayrollCompensationViewModel>();
            model.Deductions = model.Deductions ?? new List<PayrollDeductionViewModel>();
            model.DeMinimis = model.DeMinimis ?? new List<PayrollDeMinimisViewModel>();

            if (model.PaySlips == null)
            {
                return View("Index", model);
            }

            if (!ModelState.IsValid)
            {
                if (model.PaySlips.BasicSalary != 0 && model.PaySlips.EarnerType != null)   
                    return View("Index", model);
            }

            var BasicPay = ComputeExpectedPay(model.PaySlips.BasicSalary, model.PaySlips.TotalHoursWorked, model.PaySlips.ExpectedWorkedHours);

            List<PayrollCompensationViewModel> compensationsList = model.Compensations ?? new List<PayrollCompensationViewModel>();
            List<PayrollDeductionViewModel> deductionsList = model.Deductions ?? new List<PayrollDeductionViewModel>();

            // Default Values 
            var SSS = ComputeSSS(BasicPay);
            var PHIC = ComputePHIC(BasicPay);
            var PAGIBIG = ComputePAGIBIG(BasicPay);
            var OTPAY = ComputeOvertimePay(model.PaySlips.OvertimeWorkedHours == null || model.PaySlips.OvertimeWorkedHours == 0 ? 0 : (int)model.PaySlips.OvertimeWorkedHours, model.PaySlips.OvertimeRatePerHour == null || model.PaySlips.OvertimeRatePerHour == 0 ? 0 : (decimal)model.PaySlips.OvertimeRatePerHour);


            // Add Overtime if applicable    
            if (!compensationsList.Any(m => m.Compensation == CompensationType.OvertimePay) && OTPAY > 0)
            {
                var otpay_value = OTPAY > 0 ? 0 : compensationsList.Where(m => m.Compensation == CompensationType.OvertimePay).SingleOrDefault().Value;
                compensationsList.Add(new PayrollCompensationViewModel()
                {
                    Compensation = CompensationType.OvertimePay,
                    Value = otpay_value > 0 ? otpay_value : OTPAY
                });
            }
            // Add SSS if not already in list           
            if (!deductionsList.Any(m => m.Deduction == DeductionType.SSS))
            {
                deductionsList.Add(new PayrollDeductionViewModel() { Deduction = DeductionType.SSS, Value = SSS });
            }
            // Add PHIC if not already in list
            if (!deductionsList.Any(m => m.Deduction == DeductionType.PHIC))
            {
                deductionsList.Add(new PayrollDeductionViewModel() { Deduction = DeductionType.PHIC, Value = PHIC });
            }
            // Add PAGIBIG if not already in list
            if (!deductionsList.Any(m => m.Deduction == DeductionType.PAGIBIG))
            {
                deductionsList.Add(new PayrollDeductionViewModel() { Deduction = DeductionType.PAGIBIG, Value = PAGIBIG });
            }

         
            model.PaySlips.TotalDeductions = model.Deductions.Sum(m => m.Value);
            model.PaySlips.TotalDeMinimis = ComputeDeMinimis(model.DeMinimis, model.PaySlips, false);         
            model.PaySlips.TotalDeminimisExcess = ComputeDeMinimis(model.DeMinimis, model.PaySlips, true);
            model.PaySlips.TotalCompensations = model.Compensations.Sum(m => m.Value) + BasicPay + model.PaySlips.TotalDeminimisExcess;
            model.PaySlips.TaxableIncome = ComputeTaxableIncome(BasicPay + OTPAY + model.PaySlips.TotalDeminimisExcess, model.Deductions.Select(m => m.Value).ToArray());
            model.PaySlips.WithHoldingTax = ComputeTax(model.PaySlips.TaxableIncome);
            model.PaySlips.TakeHomePay = ComputeTakeHomePay(model.PaySlips.TotalCompensations + model.PaySlips.TotalDeMinimis, model.PaySlips.TotalDeductions, model.PaySlips.WithHoldingTax);

            SetDropdowns();

            return View("Index", model); ;
        }


        //public ActionResult Details()
        //{
        //    return View();
        //}

        private void SetDropdowns()
        {

            // Set list items for Compensation
            Dictionary<byte, string> compenstationDropdownList = new Dictionary<byte, string>();
            foreach (var item in Enum.GetValues(typeof(CompensationType)))
            {
                compenstationDropdownList.Add((byte)item, item.GetType().GetMember(item.ToString()).First().GetCustomAttribute<DisplayAttribute>().Name);
            }
            ViewBag.CompensationDropdownList = compenstationDropdownList;

            // Set list items for DeMinimis
            Dictionary<byte, string> deMinimisDropdownList = new Dictionary<byte, string>();
            foreach (var item in Enum.GetValues(typeof(DeMinimisType)))
            {
                deMinimisDropdownList.Add((byte)item, item.GetType().GetMember(item.ToString()).First().GetCustomAttribute<DisplayAttribute>().Name);
            }
            ViewBag.DeMinimisDropdownList = deMinimisDropdownList;

            // Set list items for Deduction
            Dictionary<byte, string> deductionDropdownList = new Dictionary<byte, string>();
            foreach (var item in Enum.GetValues(typeof(DeductionType)))
            {
                deductionDropdownList.Add((byte)item, item.GetType().GetMember(item.ToString()).First().GetCustomAttribute<DisplayAttribute>().Name);
            }
            ViewBag.DeductionDropdownList = deductionDropdownList;
        }
        public decimal ComputeSSS(decimal BasicPay)
        {
            decimal SSS = 0;

            string file = Server.MapPath("~/Controllers/SSSTable.json");
            string Json = System.IO.File.ReadAllText(file);
            JavaScriptSerializer ser = new JavaScriptSerializer();
            var SSSTable = ser.Deserialize<List<SSSTable>>(Json);

            foreach (var data in SSSTable)
            {
                if (BasicPay >= data.SalaryFrom && BasicPay < data.SalaryTo)
                {
                    SSS = data.TC_EE;
                }
                else if (BasicPay >= data.SalaryFrom && BasicPay >= data.SalaryTo)
                {
                    SSS = data.TC_EE;
                }
            }

            return SSS;
        }

        public decimal ComputePHIC(decimal BasicPay)
        {
            decimal PHIC = 0;

            if (BasicPay < 40000)
            {
                PHIC = (BasicPay * 0.0275M) / 2;
            }
            else
            {
                PHIC = 550;
            }

            return PHIC;
        }

        public decimal ComputePAGIBIG(decimal BasicPay)
        {
            decimal PAGIBIG = 0;

            if (BasicPay <= 1500)
            {
                PAGIBIG = BasicPay * 0.01M;
            }
            else
            {
                PAGIBIG = BasicPay * 0.02M;
            }

            if (PAGIBIG >= 100)
            {
                PAGIBIG = 100;
            }

            return PAGIBIG;
        }

        public decimal ComputeTaxableIncome(decimal TotalCompensation, decimal[] deductibles)
        {
            decimal TaxableIncome = 0;

            TaxableIncome = TotalCompensation - (deductibles.Sum());

            return TaxableIncome;
        }

        public decimal ComputeTax(decimal TaxableIncome)
        {
            decimal TAX = 0;

            if (TaxableIncome <= 20833)
            {
                TAX = 0;
            }
            else if (TaxableIncome > 20833 && TaxableIncome < 33333)
            {
                TAX = (TaxableIncome - 20833) * 0.20M;
            }
            else if (TaxableIncome >= 33333 && TaxableIncome < 66667)
            {
                TAX = 2500 + ((TaxableIncome - 33333) * 0.25M);
            }
            else if (TaxableIncome >= 66667 && TaxableIncome < 166667)
            {
                TAX = 10833.33M + ((TaxableIncome - 66667) * 0.30M);
            }
            else if (TaxableIncome >= 166667 && TaxableIncome < 666667)
            {
                TAX = 40833.33M + ((TaxableIncome - 166667) * 0.32M);
            }
            else if (TaxableIncome >= 666667)
            {
                TAX = 200833.33M + ((TaxableIncome - 666667) * 0.35M);
            }

            return TAX;

        }

        public decimal ComputeExpectedPay(decimal BasicPay, decimal THW, decimal EWH)
        {
            decimal ExpectedPay = 0;

            if (EWH != 0)
            {
                ExpectedPay = (THW / EWH) * BasicPay;
            }

            return ExpectedPay;
        }

        public decimal ComputeOvertimePay(decimal OTWH, decimal OTRPH)
        {
            decimal OTPAY = 0;

            OTPAY = OTWH * OTRPH;

            return OTPAY;
        }

        public decimal ComputeTakeHomePay(decimal TotalCompensations, decimal TotalDeductions, decimal WithHoldingTax)
        {
            decimal TakeHomePay = 0;

TRAIN-Calculator/Views/Payroll/Index.cshtml
@model TRAIN_Calculator.ViewModels.PayrollViewModel


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Calculate", "Payroll", FormMethod.Post, new { id = "calculator-form" }))
{
    <div class="container">

        <div class="row">
            <div class="col-md-4" id="calculate-partial-view">
                <div class="row">
                    @Html.Partial("_Calculate", Model)
                </div>

                <div class="row" style="margin-top:20px;">
                    @Html.Partial("_Contributor")
                </div>
            </div>

            <div class="col-md-8">

                <div class="row">
                    <div class="col-md-12" id="results-partial-view">
                        @Html.Partial("_Result", Model)
                    </div>
                </div>

            </div>

        </div>

    </div>
}



@section scripts{

    <script>

        $(document).ready(function () {
            DefaultValues();
        });

        $(document).on("change", ".ddl-earnerType", function () {
            DefaultValues();

        });


        function DefaultValues() {
            var earnerType = $(".ddl-earnerType option:selected").text()

            if (earnerType == "Monthly") {
                $("#PaySlips_TotalHoursWorked").val(160);
                $("#PaySlips_ExpectedWorkedHours").val(160);
            }
            else {
                $("#PaySlips_TotalHoursWorked").val("");
                $("#PaySlips_ExpectedWorkedHours").val("");
                $("#PaySlips_BasicSalary").val("");
            }

        }

        function removeCalculatorTableItem(element) {
            $(element).parent().parent().remove();
            reorderCompensation();
            reorderDeduction();
        }

        function initializeTooltip() {
            $('.tooltip-custom').tooltip({
                title: function () {
                    return tooltipContent[$(this).data('tooltip-table')][$(this).data('tooltip-item')];
                }
            })
        }

        // Compensation
        function reorderCompensation() {
            var index = 0;
            $('.compensations-table-item-key').each(function () {
                $(this).attr('name', 'Compensations[' + index + '].Compensation');
                index++;
            })

            var index = 0;
            $('.compensations-table-item-value').each(function () {
                $(this).attr('name', 'Compensations[' + index + '].Value');
                index++;
            })

            var index = 0;
            $('.deminimis-table-item-key').each(function () {
                $(this).attr('name', 'DeMinimis[' + index + '].DeMinimis');
                index++;
            })

            var index = 0;
            $('.deminimis-table-item-value').each(function () {
                $(this).attr('name', 'DeMinimis[' + index + '].Value');
                index++;
            })
        }

        function addCompensation(element) {

            var isExist = false;
            $('#compensations-table label').each(function () {
                var value = $(this).text();
                if (value == element.dataset.text)
                    isExist = true;
            })


            if (!isExist) {
                var html = $('<tr></tr>').append($('<td></td>')
                                            .append($('<input/>', { class: 'compensations-table-item-key', type: 'hidden', name: 'Compensations[0].Compensation', value: element.dataset.value }))
                                            .append($('<button></button>', { class: 'form-blank-input', onclick: 'removeCalculatorTableItem(this)' })
                                                .append($('<span></span>', { class: 'glyphicon glyphicon-minus-sign' }))))
                                        .append($('<td></td>')
                                                .append('<label>' + element.dataset.text + '</label>'))
                                        .append($('<td></td>')
                                                .append($('<img src="../Icons/tooltipicon.png" class="tooltip-custom" data-toggle="tooltip" data-tooltip-table="0" data-tooltip-item="' + element.dataset.value + '"/>')))
                                        .append($('<td></td>')
                                            .append($('<input />', { class: 'compensations-table-item-value', type: 'number', name: 'Compensations[0].Value', value: '0.00' })));
                $('#compensations-table > tbody').append(html);
                console.log(html);
                reorderCompensation();
                initializeTooltip();
            }

        }

        // Deduction
        function reorderDeduction() {
            var index = 0;
            $('.deductions-table-item-key').each(function () {
                $(this).attr('name', 'Deductions[' + index + '].Deduction');
                index++;
            })

            var index = 0;
            $('.deductions-table-item-value').each(function () {
                $(this).attr('name', 'Deductions[' + index + '].Value');
                index++;
            })
        }

        function addDeduction(element) {

            var isExist = false;
            $('#deductions-table label').each(function () {
                var value = $(this).text();
                if (value == element.dataset.text)
                    isExist = true;
            })


            if (!isExist) {

                var html = $('<tr></tr>').append($('<td></td>')
                                           .append($('<input/>', { class: 'deductions-table-item-key', type: 'hidden', name: 'Deductions[0].Deduction', value: element.dataset.value }))
                                           .append($('<button></button>', { class: 'form-blank-input', onclick: 'removeCalculatorTableItem(this)' })
                                               .append($('<span></span>', { class: 'glyphicon glyphicon-minus-sign' }))))
                                       .append($('<td></td>')
                                               .append('<label>' + element.dataset.text + '</label>'))
                                       .append($('<td></td>')
                                               .append($('<img src="../Icons/tooltipicon.png" class="tooltip-custom" data-toggle="tooltip" data-tooltip-table="2" data-tooltip-item="' + element.dataset.value + '"/>')))
                                       .append($('<td></td>')
                                           .append($('<input />', { class: 'deductions-table-item-value', type: 'number', name: 'Deductions[0].Value', value: '0.00' })));
                $('#deductions-table > tbody').append(html);


                reorderDeduction();
                initializeTooltip();
            }
        }

        // DeMinimis
        function reorderDeMinimis() {
            var index = 0;
            $('.deminimis-table-item-key').each(function () {
                $(this).attr('name', 'DeMinimis[' + index + '].DeMinimis');
                index++;
            })

            var index = 0;
            $('.deminimis-table-item-value').each(function () {
                $(this).attr('name', 'DeMinimis[' + index + '].Value');
                index++;
            })
        }

        function addDeMinimis(element) {

            var isExist = false;
            $('#compensations-table label').each(function () {
                var value = $(this).text();
                if (value == element.dataset.text)
                    isExist = true;
            })


            if (!isExist) {

                var html = $('<tr></tr>').append($('<td></td>')
                                          .append($('<input/>', { class: 'deminimis-table-item-key', type: 'hidden', name: 'DeMinimis[0].DeMinimis', value: element.dataset.value }))
                                          .append($('<button></button>', { class: 'form-blank-input', onclick: 'removeCalculatorTableItem(this)' })
                                              .append($('<span></span>', { class: 'glyphicon glyphicon-minus-sign' }))))
                                      .append($('<td></td>')
                                              .append('<label>' + element.dataset.text + '</label>'))
                                      .append($('<td></td>')
                                              .append($('<img src="../Icons/tooltipicon.png" class="tooltip-custom" data-toggle="tooltip" data-tooltip-table="1" data-tooltip-item="' + element.dataset.value + '"/>'))
                                                .append($('<img src="../Icons/tax-shield-icon.png" class="tooltip-custom" data-toggle="tooltip" title="A list of non-taxable benefits provided by BIR. Each De Minimis Benefit has limitations set by BIR, anything excess to the limit will be automatically added as Compensation which is subject to taxation"/>')))
                                      .append($('<td></td>')
                                          .append($('<input />', { class: 'deminimis-table-item-value', type: 'number', name: 'DeMinimis[0].Value', value: '0.00' })));
                $('#compensations-table > tbody').append(html);
                reorderDeMinimis();
                initializeTooltip();
            }
        }

    </script>

    <script>

        $('[data-toggle="tooltip"]').tooltip({
            title: function () {
                return tooltipContent[$(this).data('tooltip-table')][$(this).data('tooltip-item')];
            }
        });

        // [0][x] is for Compensation
        // [1][x] is for DeMinimis
        // [2][x] is for Deduction
        var tooltipContent =
            [
                [
                    // OvertimePay
                    "Total overtime pay given to an employee.",
                    // Allowance
                    "Allowance given to an employee. For example, Gas Allowance, Transportation Allowance, etc.",
                    // HolidayPay
                    "Total holiday pay given to an employee.",
                    // ECOLA
                    "Emergency Cost of Living Allowance.",
                    // ThirteenthMonthPay
                    "A non taxable compensation required by law and given at the end of the year.",
                    // Bonus
                    "An amount of money added to wages on a seasonal basis, especially as a reward for good performance.",
                    // Commission
                    "A fee for services rendered based on a percentage of an amount received or collected or agreed to be paid (as distinguished from a salary)."
                ],
                [
                    // UnusedVacationLeave
                    "Monetized unused vacation leave credits of private employees not exceeding ten(10) days during the year.",
                    // VacationandSickLeaveCredits
                    "Monetized value of vacation and sick leave dedits paid to government officials and employees.",
                    // MedicalAllowancetoEmployeeDependents
                    "Medical cash allowance to dependents of employees not exceeding P1,500.00 per employee per semester or P250.00 per month.",
                    // RiceSubsidy
                    "Rice subsidy of P2,000.00 or one(1) sack of 50kg. rice per month amounting to not more than P2,000.00",
                    // UniformandClothing
                    "Uniform ans clothing allowance not exceeding P6,000.00 per annum",
                    // MedicalExpenses
                    "Actual medical assistance, e.g. medical allowance to cover medical and healthcare needs, annual medical/executive check-up, maternity assistance, and routine consultations, not exceeding P10,000.00 per annum.",
                    // LaundryAllowance
                    "Laundry allowance not exceeding P300 per month.",
                    // AchievementAwards
                    "Employees achievement awards, e.g., for length of service or safety achievement, which must be in the form of a tangible personal property other than cash or gift certificate, with an annual monetary value not exceeding P10,000 received by the employee under an established written plan which does not discriminate in favor of highly paid employees.",
                    // ChristmasGifts
                    "Gifts given during Christmas and major anniversary celebrations not exceeding P5,000 per employee per annum.",
                    // DailyMealAllowance
                    "Daily meal allowance for overtime work and night/graveyard shift not exceeding twenty-five percent (25%) of the basic minimum wage on a per region basis.",
                    // CollectiveBargainingAgreement
                    "Benefits received by an employee by virtue of a collective bargaining agreement (CBA) and productivity incentive schemes provided that the total monetary value received from both CBA and productivity incentive schemes combined do not exceed P10,000.00 per employee per taxable year."
                ],
                [
                    // SSS
                    "Employee contribution for Social Security Services.",
                    // PAGIBIG
                    "Employee contribution for the PAGIBIG fund.",
                    // PHIC
                    "Employee contribution for the Philippine Health Insurance Corporation.",
                    // SSSLoan
                    "Payment for credit borrowed by the employee from SSS.",
                    // PAGIBIGLoan
                    "Payment for credit borrowed by the employee from PAGIBIG.",
                    // Retirement
                    "Employee's contributions given to a retirement fund.",
                    // CashAdvances
                    "Payment for the money borrowed from a creditor."
                ]
            ];

    </script>

}

TRAIN-Calculator/Views/Payroll/_Calculate.cshtml
@model TRAIN_Calculator.ViewModels.PayrollViewModel


<div class="container">
    <div class="row">
        <div id="calculator-form-container" class="form-horizontal">

            <div class="form-group">
                <div class="col-md-12">
                    @Html.LabelFor(m => m.PaySlips.EarnerType)
                    <i class="fas fa-info-circle" style="display:inline-block; color: #CFA700; margin-left:4px;" data-toggle="tooltip" data-placement="right" title="The frequency of when the employee receives their pay."></i>
                    <br />
                    @Html.EnumDropDownListFor(model => model.PaySlips.EarnerType, "Please select an Earner Type", new { @class = "form-control ddl-earnerType form-input-custom", style = "display:inline-block" })
                </div>
                <div class="col-md-12">
                    @Html.ValidationMessageFor(model => model.PaySlips.EarnerType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    @Html.LabelFor(m => m.PaySlips.TotalHoursWorked)
                    <br />
                    <span class="form-control form-input-custom">
                        <span style="border-right:1px solid #a9a9a9;color:#8c8c8c;display:inline-block;width:22%;">Hrs </span>
                        @Html.EditorFor(model => model.PaySlips.TotalHoursWorked, new { htmlAttributes = new { @class = "form-blank-input", placeholder = "000", style = "width:70%;display:inline-block;" } })
                    </span>
                    @Html.ValidationMessageFor(model => model.PaySlips.TotalHoursWorked, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(m => m.PaySlips.ExpectedWorkedHours)
                    <br />
                    <span class="form-control form-input-custom">
                        <span style="border-right:1px solid #a9a9a9;color:#8c8c8c;display:inline-block;width:22%;">Hrs </span>
                        @Html.EditorFor(model => model.PaySlips.ExpectedWorkedHours, new { htmlAttributes = new { @class = "form-blank-input", placeholder = "000", style = "width:70%;display:inline-block;" } })
                    </span>
                    @Html.ValidationMessageFor(model => model.PaySlips.ExpectedWorkedHours, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6">
                    @Html.LabelFor(m => m.PaySlips.OvertimeWorkedHours)
                    <br />
                    <span class="form-control form-input-custom">
                        <span style="border-right:1px solid #a9a9a9;color:#8c8c8c;display:inline-block;width:22%;">Hrs </span>
                        @Html.EditorFor(model => model.PaySlips.OvertimeWorkedHours, new { htmlAttributes = new { @class = "form-blank-input", placeholder = "000", style = "width:70%;display:inline-block;" } })
                    </span>
                    @Html.ValidationMessageFor(model => model.PaySlips.OvertimeWorkedHours, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(m => m.PaySlips.OvertimeRatePerHour)
                    <br />
                    <span class="form-control form-input-custom">
                        <span style="border-right:1px solid #a9a9a9;color:#8c8c8c;display:inline-block;width:22%;">Php </span>
                        @Html.EditorFor(model => model.PaySlips.OvertimeRatePerHour, new { htmlAttributes = new { @class = "form-blank-input", placeholder = "000", style = "width:70%;display:inline-block;" } })
                    </span>
                    @Html.ValidationMessageFor(model => model.PaySlips.OvertimeRatePerHour, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    @Html.LabelFor(m => m.PaySlips.BasicSalary)
                    <br />
                    <span class="form-control form-input-custom">
                        <span style="border-right:1px solid #a9a9a9;color:#8c8c8c;display:inline-block;width:22%;">Php </span>
                        @Html.EditorFor(model => model.PaySlips.BasicSalary, new { htmlAttributes = new { @class = "form-blank-input", placeholder = "000", style = "width:70%;display:inline-block;" } })
                    </span>
                    @Html.ValidationMessageFor(model => model.PaySlips.BasicSalary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group" style="margin-top:20px;">
                <div class="col-md-12">
                    <input type="submit" value="Calculate" class="btn btn-default" style="width:100%;max-width:100%;background:#CFA700;color:#fff;" />
                </div>
            </div>

        </div>
    </div>

    <div class="row">
        <p style="word-break:keep-all">This calculator will be the basis for an upcoming <nobr>open-source</nobr> library called <span style="color:#CFA700">TRAIN Engine PH</span></p>
    </div>
</div>

TRAIN-Calculator/Views/Payroll/_Contributor.cshtml
<h4 style="color:#CFA700;">Contributors</h4>

<div class="container">
    <div class="row">
        <div class="col-md-3 text-center">
            <img src="~/Content/Images/Logo/spec-black-200.jpg" class="contributor-icon" data-toggle="tooltip" data-html="true" title="<strong>Spectres.Solutions Inc.</strong><br /><p>Software Development Firm</p><strong>Description:</strong><br /><p>A design-led software development firm that specializes in cloud solutions. Spectres scales up businesses with bots, apps, sites, systems and software.</p>" />
        </div>
    </div>

    <div class="row" style="margin-top:20px;">
        <p>We are looking for more contributors both from private and government sectors. To be one of the contributors, click the link below</p>

        <p class="text-center">
            <a href="https://github.com/SpectresPH/TRAIN-Calculator">https://github.com/SpectresPH/TRAIN-Calculator</a>
        </p>
    </div>

</div>